GET http://localhost:8080 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

{
  "name": "3rd policy", 
  "type": "Garage",
  "holder_first_name": "Tenaya",
  "holder_last_name": "Pup",
  "holder_account_id": "14",
  "is_active": false,
  "has_active_claim": true,
  "effective_date": "2020-01-01",
  "termination_date": "2020-12-31"
}

###

GET http://localhost:8080/api/policies/5f98820beb05ad5c48d9b896 HTTP/1.1
content-type: application/json

###

PUT http://localhost:8080/api/policies/5f98820beb05ad5c48d9b896 HTTP/1.1
content-type: application/json

{
  "name": "Last policy",
  "holder_last_name": "olive"
}

###

DELETE http://localhost:8080/api/policies/5cccccccd00f2f7d6 HTTP/1.1
content-type: application/json

###

DELETE http://localhost:8080/api/policies HTTP/1.1
content-type: application/json