GET http://localhost:8080 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/api/policies HTTP/1.1
content-type: application/json

{
  "name": "Silver Policy",
  "type": "Renters",
  "holder_first_name": "Bailey",
  "holder_last_name": "Pup",
  "holder_account_id": "14",
  "is_active": true,
  "has_active_claim": false,
  "effective_date": "2020-01-01",
  "termination_date": "2020-12-31"
}
